networks:
  my_network:
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - my_network
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - my_network
    ports:
      - "6379:6379"

  main:
    container_name: main
    networks:
      - my_network
    build: .
    depends_on:
      - postgres
      - redis
