// Generated by dts-bundle-generator v9.5.1

import { JwtPayload } from 'jsonwebtoken';

export declare class InterfaceCasting<T, K extends keyof T> {
	[key: string]: any;
	constructor(input: T, get: readonly K[]);
	static quick<T, K extends keyof T>(input: T, get: readonly K[]): T;
	static delete<T, K extends keyof T>(input: T, get: readonly K[]): T;
}
export declare const logMethodCall: MethodDecorator$1, matching: <T>(input: T, required: T[]) => boolean;
type MethodDecorator$1 = (target: any, propertyKey: string, descriptor: PropertyDescriptor) => PropertyDescriptor;
export type MethodPrerun = (target: any, propertyKey: Function, args: any) => void;
export type MethodPostrun = (target: any, propertyKey: Function, result: any) => void;
export declare function allImplement(decorator: MethodDecorator$1): (target: Function) => void;
export declare function methodDecorator(functions: {
	prerun?: MethodPrerun;
	postrun?: MethodPostrun;
}): MethodDecorator$1;
export declare const AuthStateKeys: readonly [
	"token",
	"user"
];
export declare const IAlertKeys: readonly [
	"message",
	"object",
	"type"
];
export declare const IBaseUserInfoKeys: readonly [
	"avatarPath",
	"email",
	"id",
	"name"
];
export declare const IBaseUserEmailKeys: readonly [
	"email"
];
export declare const IBaseUserRelationshipsKeys: readonly [
	"hooks"
];
export declare const IEntityIdKeys: readonly [
	"id"
];
export declare const IBaseUserEntityKeys: readonly [
	"avatarPath",
	"email",
	"hooks",
	"id",
	"name"
];
export declare const IHookKeys: readonly [
	"fromBaseUser",
	"mtdt",
	"note",
	"signature"
];
export declare const IRecordTimeKeys: readonly [
	"createdAt",
	"updatedAt"
];
export declare const ExpectationKeys: readonly [
	"debug",
	"not",
	"params",
	"type"
];
export declare const IPayloadKeys: readonly [
	"id"
];
export declare const IAuthSignUpOptionKeys: readonly [
	"role"
];
export declare const IDeviceRelationshipKeys: readonly [
	"owner",
	"sessions"
];
export declare const IDeviceInfoKeys: readonly [
	"child",
	"hashedUserAgent",
	"id"
];
export declare const IDeviceEntityKeys: readonly [
	"child",
	"hashedUserAgent",
	"id",
	"owner",
	"sessions"
];
export declare const ISessionKeys: readonly [
	"child",
	"device",
	"parrent",
	"useTimeLeft"
];
export declare const IRefreshResultKeys: readonly [
	"hashedUserAgent",
	"sessionId",
	"status"
];
export declare const IEnterpriseInfoKeys: readonly [
	"description",
	"industry"
];
export declare const IEnterpriseAssignKeys: readonly [
	"avatarPath",
	"description",
	"email",
	"id",
	"industry",
	"name",
	"signature"
];
export declare const IEnterpriseKeys: readonly [
	"baseUser",
	"description",
	"employees",
	"industry",
	"students"
];
export declare const IEmployeeInfoKeys: readonly [
	"position"
];
export declare const IEmployeeRelationshipKeys: readonly [
	"enterprise",
	"eventCreator"
];
export declare const IEmployeeEntityKeys: readonly [
	"enterprise",
	"eventCreator",
	"position"
];
export declare const IEmployeeSignupKeys: readonly [
	"avatarPath",
	"email",
	"id",
	"name",
	"password",
	"position",
	"signature"
];
export declare const IEmployeeHookKeys: readonly [
	"avatarPath",
	"email",
	"enterpriseName",
	"id",
	"name",
	"position"
];
export declare const IEventRelationshipsKeys: readonly [
	"eventCreatedBy",
	"participators",
	"tags"
];
export declare const IEventInfoKeys: readonly [
	"additionalFields",
	"applicationDeadline",
	"description",
	"endDate",
	"id",
	"location",
	"maxParticipants",
	"positionsAvailable",
	"requiredSkills",
	"startDate",
	"status",
	"title",
	"type"
];
export declare const IEventEntityKeys: readonly [
	"additionalFields",
	"applicationDeadline",
	"description",
	"endDate",
	"eventCreatedBy",
	"id",
	"location",
	"maxParticipants",
	"participators",
	"positionsAvailable",
	"requiredSkills",
	"startDate",
	"status",
	"tags",
	"title",
	"type"
];
export declare const IEventCreatorRelationshipKeys: readonly [
	"createdEvents",
	"user"
];
export declare const IEventCreatorEntityKeys: readonly [
	"createdEvents",
	"user"
];
export declare const IEventParticipatorKeys: readonly [
	"additionalData",
	"fromEvent",
	"interviewAt",
	"interviewNote",
	"isAttended",
	"participatedBy",
	"registeredAt",
	"role",
	"status"
];
export declare const ITagRelationshipsKeys: readonly [
	"toEvents"
];
export declare const ITagInfoKeys: readonly [
	"id",
	"name"
];
export declare const ITagEntityKeys: readonly [
	"id",
	"name",
	"toEvents"
];
export declare const IFileKeys: readonly [
	"atEvent",
	"fileCreatedBy",
	"path",
	"title",
	"type",
	"uploadedAt"
];
export declare const INotificationKeys: readonly [
	"content",
	"sent",
	"title",
	"type"
];
export declare const IRecieverKeys: readonly [
	"fromNotification",
	"isRead",
	"readAt",
	"toUser"
];
export declare const IFacultyRelationshipKeys: readonly [
	"eventCreator"
];
export declare const IFacultyInfoKeys: readonly [
	"department"
];
export declare const IFacultyEntityKeys: readonly [
	"department",
	"eventCreator"
];
export declare const IFacultyAssignKeys: readonly [
	"avatarPath",
	"department",
	"email",
	"id",
	"name",
	"password",
	"signature"
];
export declare const IStudentEntityKeys: readonly [
	"currentEnterprise",
	"enrollmentYear",
	"graduationYear",
	"major",
	"skills",
	"user"
];
export declare const ISutdentRelationshipKeys: readonly [
	"currentEnterprise",
	"user"
];
export declare const IStudentInfoKeys: readonly [
	"enrollmentYear",
	"graduationYear",
	"major",
	"skills"
];
export declare const IStudentSignupKeys: readonly [
	"avatarPath",
	"email",
	"enrollmentYear",
	"graduationYear",
	"id",
	"major",
	"name",
	"password",
	"skills"
];
export declare const IUserAuthenticationKeys: readonly [
	"password"
];
export declare const IUserInfoKeys: readonly [
	"isActive",
	"lastLogin",
	"role"
];
export declare const IUserTimeRecordKeys: readonly [
	"lastLogin"
];
export declare const IUserStatusKeys: readonly [
	"isActive"
];
export declare const IUserSensitiveKeys: readonly [
	"role"
];
export declare const IUserRelationshipKeys: readonly [
	"baseUser",
	"devices",
	"participatedEvents",
	"recievedNotifications",
	"uploadFiles"
];
export declare const IUserEntityKeys: readonly [
	"baseUser",
	"devices",
	"info",
	"isActive",
	"lastLogin",
	"participatedEvents",
	"password",
	"recievedNotifications",
	"role",
	"uploadFiles"
];
export declare const IUserRecieveKeys: readonly [
	"accessToken",
	"payload",
	"refreshToken",
	"response"
];
export declare const IUserLoginKeys: readonly [
	"email",
	"password"
];
export declare const IUserSignUpKeys: readonly [
	"avatarPath",
	"email",
	"id",
	"name",
	"password"
];
export interface IHook {
	signature: string;
	fromBaseUser: IBaseUserEntity;
	mtdt: string;
	note: string;
}
export interface IBaseUserInfo extends IBaseUserEmail, IEntityId {
	name: string;
	avatarPath?: string;
}
export interface IBaseUserEmail {
	email: string;
}
export interface IBaseUserRelationships {
	hooks: IHook[];
}
export interface IEntityId {
	id?: string;
}
export interface IBaseUserEntity extends IBaseUserInfo, IBaseUserRelationships, IEntityId {
}
export interface ISession {
	device: IDeviceEntity;
	useTimeLeft: number;
	child: string;
	parrent: string;
}
export interface IDeviceRelationship {
	owner: IUserEntity;
	sessions: ISession[];
}
export interface IDeviceInfo extends IEntityId {
	child: string;
	hashedUserAgent: string;
}
export interface IDeviceEntity extends IDeviceInfo, IDeviceRelationship {
}
export interface IEventCreatorRelationship {
	user: IUserEntity;
	createdEvents: IEventEntity[];
}
export interface IEventCreatorEntity extends IEventCreatorRelationship {
}
export interface ITagRelationships {
	toEvents: IEventEntity[];
}
export interface ITagInfo extends IEntityId {
	name: string;
}
export interface ITagEntity extends ITagInfo, ITagRelationships {
}
export interface IEventRelationships {
	eventCreatedBy: IEventCreatorEntity;
	participators: IEventParticipator[];
	tags: ITagEntity[];
}
export interface IEventInfo extends IEntityId {
	title: string;
	description: string;
	startDate: Date;
	endDate: Date;
	type: EventType;
	status: EventStatus;
	positionsAvailable: number;
	maxParticipants: number;
	location: string;
	applicationDeadline: Date;
	requiredSkills: string;
	additionalFields: any;
}
export interface IEventEntity extends IEventInfo, IEventRelationships {
}
export declare enum EventStatus {
	"Draft" = "draft",
	"Published" = "published",
	"Cancelled" = "cancelled",
	"Completed" = "completed"
}
export declare enum EventType {
	"Internship" = "internship",
	"Job_fair" = "job_fair",
	"Workshop" = "workshop",
	"Seminar" = "seminar"
}
export interface IEventParticipator {
	fromEvent: IEventEntity;
	participatedBy: IUserEntity;
	role: EventParticipatorRole;
	status: EventParticipatorStatus;
	isAttended: boolean;
	registeredAt: Date;
	interviewAt: Date;
	interviewNote: string;
	additionalData: any;
}
export declare enum EventParticipatorStatus {
	registered = "registered",
	confirmed = "confirmed",
	cancelled = "cancelled",
	attended = "attended"
}
export declare enum EventParticipatorRole {
	attendee = "attendee",
	organizer = "organizer",
	speaker = "speaker"
}
export interface IFile {
	fileCreatedBy: IUserEntity;
	atEvent: IEventEntity;
	title: string;
	path: string;
	type: FileType;
	uploadedAt: Date;
}
export declare enum FileType {
	resume = "resume",
	report = "report",
	certificate = "certificate",
	other = "other"
}
export interface INotification {
	title: string;
	content: string;
	type: NotificationType;
	sent: IReciever[];
}
export declare enum NotificationType {
	event = "event",
	participation = "participator",
	progress = "progress",
	system = "system"
}
export interface IReciever {
	toUser: IUserEntity;
	fromNotification: INotification;
	isRead: boolean;
	readAt: Date;
}
export interface IUserAuthentication {
	password: string;
}
export interface IUserInfo extends IUserTimeRecord, IUserStatus, IUserSensitive {
}
export interface IUserTimeRecord {
	lastLogin: Date;
}
export interface IUserStatus {
	isActive: boolean;
}
export interface IUserSensitive {
	role: UserRole;
}
export interface IUserRelationship {
	baseUser: IBaseUserEntity;
	recievedNotifications: IReciever[];
	devices: IDeviceEntity[];
	uploadFiles: IFile[];
	participatedEvents: IEventParticipator[];
}
export interface IUserEntity extends IUserAuthentication, IUserInfo, IUserRelationship {
	readonly info: IUserInfo;
}
export interface IUserRecieve {
	accessToken: string;
	refreshToken: string;
	response: string | IUserInfo;
	payload: JwtPayload;
}
export interface IUserLogin extends IUserAuthentication, IBaseUserEmail {
}
export interface IUserSignUp extends IUserAuthentication, IBaseUserInfo {
}
export declare enum UserRole {
	student = "student",
	faculty = "faculty",
	enterprise = "enterprise",
	undefined = "undefined",
	admin = "admin"
}
export interface IAuthSignUpOption {
	role: UserRole;
}
export interface IStudentEntity extends ISutdentRelationship, IStudentInfo {
}
export interface ISutdentRelationship {
	user: IUserEntity;
	currentEnterprise: IEnterprise;
}
export interface IStudentInfo {
	major: string;
	graduationYear: number;
	enrollmentYear: number;
	skills: string;
}
export interface IStudentSignup extends IStudentInfo, IUserSignUp {
}
export interface IEmployeeInfo {
	position: EmployeePosition;
}
export interface IEmployeeRelationship {
	eventCreator: IEventCreatorEntity;
	enterprise: IEnterprise;
}
export interface IEmployeeEntity extends IEmployeeRelationship, IEmployeeInfo {
}
export interface IEmployeeSignup extends IEmployeeInfo, IUserSignUp {
	signature: string;
}
export interface IEmployeeHook extends IBaseUserInfo, IBaseUserEmail, IEmployeeInfo {
	enterpriseName: string;
}
export declare enum EmployeePosition {
	"Manager" = "manager",
	"Human_resource" = "hr",
	"Recruiter" = "recruiter",
	"Other" = "other"
}
export interface IEnterpriseInfo {
	description: string;
	industry: string;
}
export interface IEnterpriseAssign extends IEnterpriseInfo, IBaseUserInfo {
	signature: string;
}
export interface IEnterprise extends IEnterpriseInfo {
	baseUser: IBaseUserEntity;
	employees: IEmployeeEntity[];
	students: IStudentInfo[];
}
export interface IRecordTime {
	createdAt: Date;
	updatedAt: Date;
}
export declare class BlackBox implements IRecordTime {
	createdAt: Date;
	updatedAt: Date;
}
export interface IFacultyRelationship {
	eventCreator: IEventCreatorEntity;
}
export interface IFacultyInfo {
	department: string;
}
export interface IFacultyEntity extends IFacultyRelationship, IFacultyInfo {
}
export interface IFacultyAssign extends IFacultyInfo, IUserSignUp {
	signature: string;
}

export {};
