// Generated by dts-bundle-generator v9.5.1

import { JwtPayload } from 'jsonwebtoken';

export interface IHook {
	signature: string;
	fromBaseUser: IBaseUserEntity;
	mtdt: string;
	note: string;
}
export interface IBaseUserInfo extends IBaseUserEmail, IEntityId {
	name: string;
	avatarPath?: string;
}
export interface IBaseUserEmail {
	email: string;
}
export interface IBaseUserRelationships {
	hooks: IHook[];
}
export interface IEntityId {
	id?: string;
}
export interface IBaseUserEntity extends IBaseUserInfo, IBaseUserRelationships, IEntityId {
}
export interface ISession {
	device: IDeviceEntity;
	useTimeLeft: number;
	child: string;
	parrent: string;
}
export interface IDeviceRelationship {
	owner: IUserEntity;
	sessions: ISession[];
}
export interface IDeviceInfo extends IEntityId {
	child: string;
	hashedUserAgent: string;
}
export interface IDeviceEntity extends IDeviceInfo, IDeviceRelationship {
}
export interface IEventCreatorRelationship {
	user: IUserEntity;
	createdEvents: IEventEntity[];
}
export interface IEventCreatorEntity extends IEventCreatorRelationship {
}
export interface ITagRelationships {
	toEvents: IEventEntity[];
}
export interface ITagInfo extends IEntityId {
	name: string;
}
export interface ITagEntity extends ITagInfo, ITagRelationships {
}
export interface IEventRelationships {
	eventCreatedBy: IEventCreatorEntity;
	participators: IEventParticipatorEntiy[];
	tags: ITagEntity[];
}
export interface IEventInfo extends IEntityId {
	title: string;
	description: string;
	startDate: Date;
	endDate: Date;
	type: EventType;
	status: EventStatus;
	positionsAvailable: number;
	maxParticipants: number;
	location: string;
	applicationDeadline: Date;
	requiredSkills: string;
	additionalFields?: object;
}
export interface IEventEntity extends IEventInfo, IEventRelationships {
}
export declare enum EventStatus {
	"Draft" = "draft",
	"Published" = "published",
	"Cancelled" = "cancelled",
	"Completed" = "completed"
}
export declare enum EventType {
	"Internship" = "internship",
	"Job_fair" = "job_fair",
	"Workshop" = "workshop",
	"Seminar" = "seminar"
}
export interface IEventParticipatorRelationships {
	fromEvent: IEventEntity;
	participatedBy: IUserEntity;
}
export interface IEventParticipatorInfo extends IEntityId {
	role: EventParticipatorRole;
	status: EventParticipatorStatus;
	isAttended: boolean;
	registeredAt: Date;
	interviewAt: Date;
	interviewNote: string;
	additionalData: object;
}
export interface IEventParticipatorEntiy extends IEventParticipatorInfo, IEventParticipatorRelationships {
}
export declare enum EventParticipatorStatus {
	registered = "registered",
	confirmed = "confirmed",
	cancelled = "cancelled",
	attended = "attended"
}
export declare enum EventParticipatorRole {
	attendee = "attendee",
	organizer = "organizer",
	speaker = "speaker"
}
export interface IFile {
	fileCreatedBy: IUserEntity;
	atEvent: IEventEntity;
	title: string;
	path: string;
	type: FileType;
	uploadedAt: Date;
}
export declare enum FileType {
	resume = "resume",
	report = "report",
	certificate = "certificate",
	other = "other"
}
export interface INotificationInfo extends IEntityId {
	title: string;
	content: string;
	type: NotificationType;
}
export interface INotificationRelationship {
	sent: IRecieverEntity[];
}
export interface INotificationEntity extends INotificationInfo, INotificationRelationship {
}
export declare enum NotificationType {
	event = "event",
	participation = "participator",
	progress = "progress",
	system = "system"
}
export interface IRecieverInfo extends IEntityId {
	isRead: boolean;
	readAt: Date;
}
export interface IRecieverRelationships {
	toUser: IUserInfo;
	fromNotification: INotificationInfo;
}
export interface IRecieverEntity extends IRecieverRelationships, IRecieverInfo {
}
export interface IUserAuthentication {
	password: string;
}
export interface IUserInfo extends IUserTimeRecord, IUserStatus, IUserSensitive {
}
export interface IUserTimeRecord {
	lastLogin: Date;
}
export interface IUserStatus {
	isActive: boolean;
}
export interface IUserSensitive {
	role: UserRole;
}
export interface IUserRelationship {
	baseUser: IBaseUserEntity;
	recievedNotifications: IRecieverEntity[];
	devices: IDeviceEntity[];
	uploadFiles: IFile[];
	participatedEvents: IEventParticipatorEntiy[];
}
export interface IUserEntity extends IUserAuthentication, IUserInfo, IUserRelationship {
	readonly info: IUserInfo;
}
export interface IUserRecieve {
	accessToken: string;
	refreshToken: string;
	response: string | IUserInfo;
	payload: JwtPayload;
}
export interface IUserLogin extends IUserAuthentication, IBaseUserEmail {
}
export interface IUserSignUp extends IUserAuthentication, IBaseUserInfo {
}
export declare enum UserRole {
	student = "student",
	faculty = "faculty",
	enterprise = "enterprise",
	undefined = "undefined",
	admin = "admin"
}
export interface IAuthSignUpOption {
	role: UserRole;
}
export interface IStudentEntity extends ISutdentRelationship, IStudentInfo {
}
export interface ISutdentRelationship {
	user: IUserEntity;
	currentEnterprise: IEnterprise;
}
export interface IStudentInfo {
	major: string;
	graduationYear: number;
	enrollmentYear: number;
	skills: string;
}
export interface IStudentSignup extends IStudentInfo, IUserSignUp {
}
export interface IEnterpriseInfo {
	description: string;
	industry: string;
}
export interface IEnterpriseAssign extends IEnterpriseInfo, IBaseUserInfo {
	signature: string;
}
export interface IEnterprise extends IEnterpriseInfo {
	baseUser: IBaseUserEntity;
	employees: IEmployeeEntity[];
	students: IStudentInfo[];
}
export interface IEmployeeInfo {
	position: EmployeePosition;
}
export interface IEmployeeRelationship {
	eventCreator: IEventCreatorEntity;
	enterprise: IEnterprise;
}
export interface IEmployeeEntity extends IEmployeeRelationship, IEmployeeInfo {
}
export interface IEmployeeSignup extends IEmployeeInfo, IUserSignUp {
	signature: string;
}
export interface IEmployeeHook extends IBaseUserInfo, IBaseUserEmail, IEmployeeInfo {
	enterpriseName: string;
}
export declare enum EmployeePosition {
	"Manager" = "manager",
	"Human_resource" = "hr",
	"Recruiter" = "recruiter",
	"Other" = "other"
}
export interface IFacultyRelationship {
	eventCreator: IEventCreatorEntity;
}
export interface IFacultyInfo {
	department: string;
}
export interface IFacultyEntity extends IFacultyRelationship, IFacultyInfo {
}
export interface IFacultyAssign extends IFacultyInfo, IUserSignUp {
	signature: string;
}

export {};
