name: Package compiler

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: 'Compile'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ github.token }}

      - name: Configure git
        run: |
          git config user.name "GitHubActions"
          git config user.email "<>"

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - run: pnpm install

      - run: 'npm run build & npm run doc'

      - run: 'cp README.md LICENSE ./types'

      - uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ github.token }}
          publish_dir: types
          publish_branch: package
          force_orphan: true

      - uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ github.token }}
          publish_dir: documentation
          publish_branch: documentation
          force_orphan: true

      - run: npx semantic-release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ github.token }}
