name: Package compiler

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: 'Compile'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - run: pnpm install

      - run: npx semantic-release
        if: github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: leigholiver/commit-with-deploy-key@v1.0.4
        if: github.ref == 'refs/heads/master'
        with:
          source: .
          destination_branch: master
          destination_repo: 524H0003/Project_W
          deploy_key: ${{ secrets.DEPLOY_KEY }}

      - run: 'cp README.md LICENSE ./types'

      - uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ github.token }}
          publish_dir: types
          publish_branch: package
          force_orphan: true
